In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("Titanic-Dataset.csv")
df[["Survived", "Name", "Sex","Age","Fare"]]

,Survived,Name,Sex,Age,Fare
0,0,"Braund, Mr. Owen Harris",male,22.0,7.2500
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833
2,1,"Heikkinen, Miss. Laina",female,26.0,7.9250
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000
4,0,"Allen, Mr. William Henry",male,35.0,8.0500
...,...,...,...,...,...
886,0,"Montvila, Rev. Juozas",male,27.0,13.0000
887,1,"Graham, Miss. Margaret Edith",female,19.0,30.0000
888,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500
889,1,"Behr, Mr. Karl Howell",male,26.0,30.0000
890,0,"Dooley, Mr. Patrick",male,32.0,7.7500

In [14]:
result = df[(df["Sex"] == "female") & (df["Fare"] > 30) ]
print(result)

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
9             10         1       2
25            26         1       3
31            32         1       1
..           ...       ...     ...
853          854         1       1
856          857         1       1
863          864         0       3
871          872         1       1
879          880         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1
..                                                 ...     ...   ...    ...
853                          Lines, Miss. Mary Conover  female  16.0      0
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.0      1
863                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN      8
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0

     Parch    Ticket      Fare Cabin Embarked
1        0  PC 17599   71.2833   C85        C
3        0    113803   53.1000  C123        S
9        0    237736   30.0708   NaN        C
25       5    347077   31.3875   NaN        S
31       0  PC 17569  146.5208   B78        C
..     ...       ...       ...   ...      ...
853      1  PC 17592   39.4000   D28        S
856      1     36928  164.8667   NaN        S
863      2  CA. 2343   69.5500   NaN        S
871      1     11751   52.5542   D35        S
879      1     11767   83.1583   C50        C

[113 rows x 12 columns]

In [15]:
df.groupby("Pclass").agg({
    "Survived" : "mean",
    "Fare"  : "mean",
    "Age"  : "mean"
})

        Survived       Fare        Age
Pclass
1       0.629630  84.154687  38.233441
2       0.472826  20.662183  29.877630
3       0.242363  13.675550  25.140620